### ISSUE TITLE
 Is it done yet?

### ISSUE THREAD

**Issue by matthew4444** [EnderManiacsKingdom/TNTRUN#1]
Can i relase it on the fourms yet?

**Comment by matthew4444** [comment]
can u add this to gladiatormine?https://github.com/EnderManiacsKingdom/GladiatiorMine-API-Souce-Code

**Comment by erkam2002** [comment]
later

**Comment by erkam2002** [comment]
is to difficult

**Comment by erkam2002** [comment]
Nether is implemeted

**Comment by matthew4444** [comment]
kk

**Comment by matthew4444** [comment]
can we finish some of our https://github.com/EnderManiacsKingdom/WorkingInProgress-Plugins-Sourcecode-For-Dev, and can i be a admin on your cool server im TheEnderCreeper0

**Comment by DavidJBrockway** [comment]
hey i am still working on this

**Comment by DavidJBrockway** [comment]
i have made some stuff

**Comment by DavidJBrockway** [comment]
almost done need testing

**Comment by DavidJBrockway** [comment]
The Plugin is done

**Comment by DavidJBrockway** [comment]
i have removed wokring in progress plugins as we need to make plugins one by one

**Comment by DavidJBrockway** [comment]
i work on uhc and enderauth

**Comment by NetherOwner** [comment]
Thank you david

**Comment by DavidJBrockway** [comment]
Plz will you up,aid ended source code

**Comment by DavidJBrockway** [comment]
This plugin is not ready for the formus and should. Be paid on formus
